article/urls.py
from django.urls import path

from .views import (
    article_list_view,
    article_detail_view,
)
app_name = 'article'

urlpatterns = [
    path('list/', article_list_view, name='list'),
    path('detail/<slug:slug>/', article_detail_view, name='detail')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('article', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import (
    home_view,
    about_view,
    contact_view,
)


app_name = 'main'

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('contact/', contact_view, name='contact')
]

article/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.db.models.signals import pre_save
from django.utils import timezone


class Category(models.Model):
    title = models.CharField(max_length=123)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=123)

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to='authors/')
    bio = models.TextField()

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)
    title = models.CharField(max_length=123)
    slug = models.SlugField(editable=False, null=True, blank=True)
    image = models.ImageField(upload_to='articles/')
    content = RichTextField()
    tags = models.ManyToManyField(Tag)
    modified_date = models.DateTimeField(auto_now=True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class SubArticle(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, related_name='subarticles')
    title = models.CharField(max_length=123)
    header_content = RichTextField(null=True, blank=True)
    image = models.ImageField(upload_to='articles/')
    footer_content = RichTextField(null=True, blank=True)
    modified_date = models.DateTimeField(auto_now=True)
    create_date = models.DateTimeField(auto_now_add=True)
    

class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    name = models.CharField(max_length=123)
    image = models.ImageField(upload_to='articles/comments/', null=True, blank=True)
    message = models.TextField()
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def get_image(self):
        if self.image:
            return mark_safe(f'<a href="{self.image.url}" target="_blank"><img src="{self.image.url}" width="50" height="50" /></a>')
        return '-'


def article_pre_save(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title + "-" + str(timezone.now().date()))


pre_save.connect(article_pre_save, sender=Article)

main/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=123)
    email = models.EmailField(max_length=123, null=True, blank=True)
    subject = models.CharField(max_length=123, null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    name = models.CharField(max_length=255)
    position = models.CharField(max_length=255)
    image = models.ImageField(upload_to='feedback/')
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

article/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Article, Tag, Comment, Category
from django.core.paginator import Paginator
from .form import CommentForm


def article_list_view(request):
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    articles = Article.objects.order_by('-id')
    page = request.GET.get('page')
    paginator = Paginator(articles, 3)
    page_obj = paginator.get_page(page)
    if cat:
        page_obj = articles.filter(category__title__exact=cat)

    if tag:
        page_obj = articles.filter(tags__title__exact=tag)
    q = request.GET.get('q')
    if q:
        page_obj = Article.objects.filter(title__icontains=q).order_by('-id')
    ctx = {
        'object_list': page_obj,
    }
    return render(request, 'article/blog.html', ctx)


def article_detail_view(request, slug):
    article = get_object_or_404(Article, slug=slug)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.article = article
            obj.save()
            return redirect('.#comment-list')
    ctx = {
        'object': article,
        'categories': categories,
        'tags': tags,
        'form': form,
    }
    return render(request, 'article/blog-single.html', ctx)

main/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib import messages
from article.models import Article
from .models import Feedback, Contact
from .form import ContactForm


def home_view(request):
    articles = Article.objects.order_by('-id')
    paginator = Paginator(articles, 3)
    page = request.GET.get('page')
    page_obj = paginator.get_page(page)
    ctx = {
        'articles': page_obj,
    }
    return render(request, 'main/index.html', ctx)


def about_view(request):
    feedbacks = Feedback.objects.all()
    ctx = {
        'object_list': feedbacks
    }
    return render(request, 'main/about.html', ctx)


def contact_view(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your message successfully sent')
            return redirect('.#django-messages')
    ctx = {
        'form': form
    }
    return render(request, 'main/contact.html', ctx)

templates/article/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


{% load footer_articles %}
{% last_two_articles as last_two_articles %}
    <section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Blog Single</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:home' %}">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a
                            href="{% url 'article:list' %}">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <p class="mb-5">
                        <img src="{{ object.image.url }}" alt class="img-fluid">
                    </p>
                    <h2 class="mb-3">{{ object.title }}</h2>
                    <p>{{ object.content|safe }}</p>
                    {% for foo in object.subarticles.all %}

                        <h2 class="mb-3 mt-5">#{{ forloop.counter|add:'1' }}. {{ foo.title }}</h2>
                        <p>{{ foo.header_content|safe }}</p>
                        <p class="mb-5">
                            <img src="{{ foo.image.url }}" alt class="img-fluid">
                        </p>
                        <p>{{ foo.footer_content|safe }}</p>
                    {% endfor %}
                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">
                            {% for tag in object.tags.all %}

                                <a href="{% url 'article:list' %}?tag={{ tag.title }}" class="tag-cloud-link">{{ tag.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    {% if object.author %}
                        <div class="about-author d-flex p-4 bg-light">
                            <div class="bio mr-5">
                                <img src="{{ object.author.image.url }}" alt="Image placeholder" class="img-fluid mb-4">
                            </div>
                            <div class="desc">
                                <h3>{{ object.author.name }}</h3>
                                <p>{{ object.author.bio }}</p>
                            </div>
                        </div>
                    {% endif %}
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">{{ object.comment_set.count }} Comments</h3>
                        <ul class="comment-list">
                            {% for comment in object.comment_set.all|dictsortreversed:'id' %}
                            <li class="comment">
                                <div class="vcard bio">
                                    <img src="{% if comment.image %}{{ comment.image.url }}{% else %}{% static 'images/24-248253_user-profile-default-image-png-clipart-png-download.png' %} {% endif %}" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                    <h3>{{ comment.name }}</h3>
                                    <div class="meta mb-3">{{ comment.created_date|date:"F d, Y \a\t h:mA" }}</div>
                                    <p>{{ comment.message }}</p>
                                </div>
                            </li>
                              {% endfor %}
                        </ul>

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                        <form method="post" enctype="multipart/form-data" class="p-5 bg-light">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="name">Name *</label>
                                {{ form.name }}
                            </div>
                            <div class="form-group">
                                <label for="file">Image</label>
                                {{ form.image }}
                            </div>
                            <div class="form-group">
                                <label for="message">Message</label>
                                {{ form.message }}
                            </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                    <div class="sidebar-box">
                        <form action="{% url 'article:list' %}" method="get" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">

                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <div class="categories">
                            <h3>Categories</h3>
                            <li><a href="{% url 'article:list' %}">All <span
                                    class="ion-ios-arrow-forward"></span></a></li>

                            {% for category in categories %}
                                <li><a href="{% url 'article:list' %}?cat={{ category.title }}">{{ category.title }}
                                    <span class="ion-ios-arrow-forward"></span></a></li>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Recent Blog</h3>
                        {% for last_two_article in last_two_articles %}

                            <div class="block-21 mb-4 d-flex">
                                <a class="blog-img mr-4"
                                   style="background-image: url({{ last_two_article.image.url }});"></a>
                                <div class="text">
                                    <h3 class="heading"><a href="{% url 'article:detail' last_two_article.slug %}">{{ last_two_article.title }}</a></h3>
                                    <div class="meta">
                                        <div><a href="#"><span class="icon-calendar"></span> {{ last_two_article.created_date|date:"M d, Y" }}</a></div>
                                        <div><a href="#"><span class="icon-person"></span> {{ last_two_article.author.name }}</a></div>
                                        <div><a href="#"><span class="icon-chat"></span> {{ last_two_article.comment_set.count }}</a></div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            {% for tag in tags %}
                                
                            <a href="{% url 'article:list' %}?tag={{ tag.title }}" class="tag-cloud-link">{{ tag.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Paragraph</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/article/blog.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
         data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
                 data-scrollax-parent="true">
                <div class="col-md-12 ftco-animate">
                    <h2 class="subheading">Hello! Welcome to</h2>
                    <h1 class="mb-4 mb-md-0">Readit blog</h1>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="text">
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                    Consonantia,
                                    there live the blind texts. Separated they live in Bookmarksgrove right at the coast
                                    of
                                    the Semantics, a large language ocean.</p>
                                <div class="mouse">
                                    <a href="{% url 'article:list' %}" class="mouse-icon">
                                        <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row d-flex">
                {% for object in object_list %}



                    <div class="col-md-4 d-flex ftco-animate">
                        <div class="blog-entry justify-content-end">
                            <a href="{% url 'article:detail' object.slug %}" class="block-20"
                               style="background-image: url({{ object.image.url }});">
                            </a>
                            <div class="text p-4 float-right d-block">
                                <div class="topper d-flex align-items-center">
                                    <div class="one py-2 pl-3 pr-1 align-self-stretch">
                                        <span class="day">{{ object.created_date.day }}</span>
                                    </div>
                                    <div class="two pl-0 pr-3 py-2 align-self-stretch">
                                        <span class="yr">{{ object.created_date.year }}</span>
                                        <span class="mos">{{ object.created_date|date:'F' }}</span>
                                    </div>
                                </div>
                                <h3 class="heading mb-3"><a href="{% url 'article:detail' object.slug %}">{{ object.title }}</a></h3>
                                <p>{{ object.content|safe|slice:":80" }}...</p>
                                <p><a href="{% url 'article:detail' object.slug %}" class="btn-custom"><span class="ion-ios-arrow-round-forward mr-3"></span>Read
                                    more</a></p>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% include 'paginator.html' %}
        </div>
    </section>
{% endblock %}

templates/footer.html
{% load static %}
{% load footer_articles %}
{% last_two_articles as footer_articles %}


<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="logo"><a href="{% url 'article:list' %}">Read<span>it</span>.</a></h2>
                    <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there
                        live the blind texts.</p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate"><a target="_blank" href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-twitter"></span></a></li>
                        <li class="ftco-animate"><a target="_blank"  href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-facebook"></span></a></li>
                        <li class="ftco-animate"><a target="_blank" href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-instagram"></span></a></li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">latest News</h2>

                    {% for footer_article in footer_articles %}
                        <div class="block-21 mb-4 d-flex">
                            <a class="img mr-4 rounded"
                               style="background-image: url({{ footer_article.image.url }});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="{% url 'article:detail' footer_article.slug %}">{{ footer_article.title }}</a></h3>
                                <div class="meta">
                                    <div><a href="{% url 'article:detail' footer_article.slug %}"></span> {{ footer_article.created_date|date:"M d,Y" }}</a></div>
                                    <div><a href="{% url 'article:detail' footer_article.slug %}"></span> {{ footer_article.author.name }}</a></div>
                                    <div><a href="{% url 'article:detail' footer_article.slug %}"><span class="icon-chat"></span> {{ footer_article.comment_set.count }}</a></div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Information</h2>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'main:home' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Home</a>
                        </li>
                        <li><a href="{% url 'main:about' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>About</a>
                        </li>
                        <li><a href="{% url 'article:list' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Articles</a></li>
                        <li><a href="{% url 'main:contact' %}" class="py-1 d-block"><span
                                class="ion-ios-arrow-forward mr-3"></span>Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Have a Questions?</h2>
                    <div class="block-23 mb-3">
                        <ul>
                            <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span>
                            </li>
                            <li><a href="#"><span class="icon icon-phone"></span><span
                                    class="text">+2 392 3929 210</span></a></li>
                            <li><a href="#"><span class="icon icon-envelope"></span><span class="text"><span
                                    class="__cf_email__" data-cfemail="472e292128073e28323523282a262e296924282a">[email&#160;protected]</span></span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    Copyright &copy;<script data-cfasync="false"
                                            src="https://preview.colorlib.com/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js"></script>
                    <script>document.write(new Date().getFullYear());</script>
                    All rights reserved | This template is made with <i class="icon-heart color-danger"
                                                                        aria-hidden="true"></i> by <a
                        href="https://colorlib.com/" target="_blank">Colorlib</a>
                </p>
            </div>
        </div>
    </div>
</footer>

templates/loader.html
{#<div id="ftco-loader" class="show fullscreen">#}
{#    <svg class="circular" width="48px" height="48px">#}
{#        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>#}
{#        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"#}
{#                stroke="#F96D00"/>#}
{#    </svg>#}
{#</div>#}

templates/main/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="hero-wrap js-fullheight" style="background-image: url({% static 'images/bg_1.jpg' %});"
         data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-center justify-content-start"
                 data-scrollax-parent="true">
                <div class="col-md-12 ftco-animate">
                    <h2 class="subheading">Hello! Welcome to</h2>
                    <h1 class="mb-4 mb-md-0">Readit blog</h1>
                    <div class="row">
                        <div class="col-md-7">
                            <div class="text">
                                <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                    Consonantia,
                                    there live the blind texts. Separated they live in Bookmarksgrove right at the coast
                                    of
                                    the Semantics, a large language ocean.</p>
                                <div class="mouse">
                                    <a href="{% url 'article:list' %}" class="mouse-icon">
                                        <div class="mouse-wheel"><span class="ion-ios-arrow-round-down"></span></div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

    <section class="ftco-section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">

                {% for article in articles %}
                    <div class="case">
                        <div class="row">
                            <div class="col-md-6 col-lg-6 col-xl-8 d-flex">
                                <a href="{% url 'article:detail' article.slug %}" class="img w-100 mb-3 mb-md-0"
                                   style="background-image: url({{ article.image.url }});"></a>
                            </div>
                            <div class="col-md-6 col-lg-6 col-xl-4 d-flex">
                                <div class="text w-100 pl-md-3">
                                    <span class="subheading">{{ article.category.title }}</span>
                                    <h2><a href="{% url 'article:detail' article.slug %}">{{ article.title }}</a></h2>
                                    <ul class="media-social list-unstyled">
                                        <li class="ftco-animate"><a target="_blank" href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-twitter"></span></a></li>
                                        <li class="ftco-animate"><a target="_blank" href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-facebook"></span></a></li>
                                        <li class="ftco-animate"><a target="_blank" href="https://www.instagram.com/khudoykulov257?igsh=bjRybm4zcm15d2Vx"><span class="icon-instagram"></span></a></li>
                                    </ul>
                                    <div class="meta">
                                        <p class="mb-0"><a href="#">{{ article.created_date|date:"d/m/y" }}</a> | <a href="#">12 min read</a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}


            </div>
        </div>

        {% include 'paginator.html' with object_list=articles %}

    </div>
</section>

{% endblock %}

templates/navbar.html
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="{% url 'main:home' %}">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'main:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'article:list' %}" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="{% url 'main:about' %}" class="nav-link">Team</a></li>
                <li class="nav-item"><a href="{% url 'main:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>

templates/paginator.html
<div class="row mt-5">
    <div class="col text-center">
        <div class="block-27">
            <ul>
                {% if object_list.has_previous %}
                    <li><a href="?page={{ object_list.previous_page_number }}">&lt;</a></li>
                {% endif %}

                {% for page_number in object_list.paginator.page_range %}
                    <li class="{% if object_list.number == page_number %}active{% endif %}"><a href="?page={{ page_number }}"><span>{{ page_number }}</span></a></li>
                {% endfor %}

                {% if object_list.has_next %}
                    <li><a href="?page={{ object_list.next_page_number }}">&gt;</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>